(function () {
  "use strict";

  const chapters = [
    {
      id: "first-meet",
      step: 1,
      title: "AI와의 첫 만남",
      description: "아직 어색한 사이인지, 제법 친한 사이인지 확인해볼게요.",
      kicker: "첫 인상 체크",
      pause: "정답을 고르는 시간이 아니에요. 어깨에 힘을 빼고 첫 느낌을 따라가요.",
      prompt: "어깨 힘 빼기 완료",
      color: "#a999ff",
      image: "./assets/steps/step-1-first-meet.png",
    },
    {
      id: "history",
      step: 2,
      title: "나의 AI 사용 기록",
      description: "업무와 일상에서 AI를 얼마나 만나봤을까요?",
      kicker: "사용 기록 탐색",
      pause: "내가 AI를 썼던 가장 최근 순간을 잠깐 떠올려보세요.",
      prompt: "기억 소환 완료",
      color: "#7ea5d8",
      image: "./assets/steps/step-2-usage-history.png",
    },
    {
      id: "sense",
      step: 3,
      title: "AI 센스 체크",
      description: "헷갈리기 쉬운 핵심 포인트만 가볍게 살펴봅니다.",
      kicker: "센스 체크",
      pause: "이제부터는 짧은 해설이 바로 나와요. 틀려도 배운 순간이 곧 정답!",
      prompt: "탐정 모드 ON",
      color: "#78cfb3",
      image: "./assets/steps/step-3-ai-sense.png",
    },
    {
      id: "prompt",
      step: 4,
      title: "프롬프트 스타일링",
      description: "AI가 알아듣기 좋은 요청으로 바꿔볼 시간이에요.",
      kicker: "질문 스타일링",
      pause: "좋은 질문은 완벽한 주문이 아니라, 잘 쓴 업무 브리프에 가까워요.",
      prompt: "브리프 준비 완료",
      color: "#e9ad4e",
      image: "./assets/steps/step-4-prompt-styling.png",
    },
    {
      id: "review",
      step: 5,
      title: "AI 결과물 검수실",
      description: "자연스럽게 말하는 AI의 결과, 어디까지 믿어도 될까요?",
      kicker: "결과물 검수",
      pause: "잠깐 눈을 쉬고, 이제 AI 결과 속 빈틈을 찾아볼까요?",
      prompt: "돋보기 장착 완료",
      color: "#ee9968",
      image: "./assets/steps/step-5-result-review.png",
    },
    {
      id: "rescue",
      step: 6,
      title: "나의 업무 구조대 요청",
      description: "AI가 가장 먼저 도와줬으면 하는 일을 알려주세요.",
      kicker: "마지막 구조 요청",
      pause: "거의 다 왔어요. 마지막에는 정답 없이, 내가 원하는 변화만 고르면 돼요.",
      prompt: "마지막 스퍼트",
      color: "#e97f93",
      image: "./assets/steps/step-6-rescue-request.png",
    },
  ];

  const jobTasks = [
    { value: "writing", label: "이메일·메신저 작성", icon: "💬" },
    { value: "report", label: "보고서·기획서 작성", icon: "📝" },
    { value: "meeting", label: "회의 준비·회의록 정리", icon: "🗒️" },
    { value: "research", label: "자료 조사", icon: "🔎" },
    { value: "data", label: "엑셀·데이터 처리", icon: "📊" },
    { value: "presentation", label: "발표자료 작성", icon: "📑" },
    { value: "project", label: "일정·프로젝트 관리", icon: "📅" },
    { value: "support", label: "고객·임직원 문의 대응", icon: "🎧" },
    { value: "ideas", label: "아이디어 도출", icon: "💡" },
    { value: "other", label: "기타 업무", icon: "✨" },
  ];

  const questions = [
    {
      id: "Q1",
      chapter: "first-meet",
      dimension: "awareness",
      type: "single",
      title: "업무가 막혔을 때 AI에게 도움을 요청하는 것은 어떤 느낌인가요?",
      helper: "지금 내 마음과 가장 가까운 답을 골라주세요.",
      options: [
        { value: "a", label: "아직은 조금 부담스럽다", score: 0, icon: "😶‍🌫️" },
        { value: "b", label: "필요하면 한번 물어볼 수 있다", score: 1, icon: "🙂" },
        { value: "c", label: "제법 유용할 것 같아 기대된다", score: 2, icon: "✨" },
        { value: "d", label: "이미 든든한 업무 파트너라고 생각한다", score: 3, icon: "🤝" },
      ],
    },
    {
      id: "Q2",
      chapter: "first-meet",
      dimension: "awareness",
      type: "single",
      title: "오늘 오후까지 보고서 초안을 써야 하는데 첫 문장이 떠오르지 않습니다.",
      helper: "가장 가까운 행동은 무엇인가요?",
      options: [
        { value: "a", label: "일단 다른 일을 하며 미룬다", score: 0 },
        { value: "b", label: "기존 보고서를 찾아본다", score: 1 },
        { value: "c", label: "AI에게 목차나 초안을 요청해본다", score: 3 },
        { value: "d", label: "동료에게 먼저 물어본 뒤 AI도 활용한다", score: 2 },
      ],
    },
    {
      id: "Q3",
      chapter: "first-meet",
      type: "single",
      tag: "anxiety",
      title: "AI를 업무에 사용할 때 가장 걱정되는 것은 무엇인가요?",
      options: [
        { value: "prompt_anxiety", label: "무엇을 물어봐야 할지 모르겠다" },
        { value: "accuracy_anxiety", label: "답변이 틀릴까 봐 걱정된다" },
        { value: "security_anxiety", label: "회사 정보를 입력해도 되는지 모르겠다" },
        { value: "quality_anxiety", label: "결과가 너무 뻔하거나 마음에 들지 않는다" },
        { value: "efficiency_anxiety", label: "사용하다가 오히려 시간이 더 걸릴 것 같다" },
        { value: "no_anxiety", label: "특별히 걱정되는 것은 없다" },
      ],
    },
    {
      id: "Q4",
      chapter: "first-meet",
      dimension: "awareness",
      type: "single",
      title: "AI에게 처음 보는 업무를 맡겨보라는 제안을 받았습니다. 나의 반응은?",
      options: [
        { value: "a", label: "실패할 것 같아 기존 방식으로 처리한다", score: 0 },
        { value: "b", label: "다른 사람이 사용하는 모습을 먼저 본다", score: 1 },
        { value: "c", label: "작은 부분부터 시험해본다", score: 2 },
        { value: "d", label: "일단 시도하고 결과를 비교해본다", score: 3 },
      ],
    },
    {
      id: "Q5",
      chapter: "history",
      dimension: "experience",
      type: "single",
      title: "최근 한 달 동안 생성형 AI를 얼마나 사용했나요?",
      helper: "업무와 개인적인 사용을 모두 포함해 주세요.",
      options: [
        { value: "a", label: "한 번도 사용하지 않았다", score: 0 },
        { value: "b", label: "한두 번 사용했다", score: 1 },
        { value: "c", label: "주 1~2회 사용했다", score: 2 },
        { value: "d", label: "주 3~4회 사용했다", score: 3 },
        { value: "e", label: "거의 매일 사용했다", score: 4 },
      ],
    },
    {
      id: "Q6",
      chapter: "history",
      dimension: "experience",
      type: "multi",
      scoring: "experienceCount",
      title: "실제로 AI에게 해본 일을 모두 선택해주세요.",
      helper: "해본 적 있는 만큼 골라도 괜찮아요.",
      options: [
        { value: "message", label: "이메일·메신저 문장 작성" },
        { value: "summary", label: "긴 글이나 자료 요약" },
        { value: "draft", label: "보고서·기획서 초안" },
        { value: "ideas", label: "아이디어 추천" },
        { value: "research", label: "자료 조사" },
        { value: "translation", label: "번역·문장 다듬기" },
        { value: "data", label: "엑셀 함수·데이터 분석" },
        { value: "image", label: "이미지 제작" },
        { value: "planning", label: "일정·계획 정리" },
        { value: "automation", label: "코딩·자동화" },
        { value: "none", label: "아직 사용해본 적 없음", exclusive: true },
      ],
    },
    {
      id: "Q7",
      chapter: "history",
      dimension: "experience",
      type: "single",
      title: "AI를 사용할 때 가장 가까운 모습은?",
      options: [
        { value: "a", label: "다른 사람이 알려준 문장을 그대로 입력한다", score: 0 },
        { value: "b", label: "인터넷에서 프롬프트 예시를 찾아 입력한다", score: 1 },
        { value: "c", label: "상황에 맞게 질문을 조금씩 수정한다", score: 2 },
        { value: "d", label: "결과를 보며 여러 번 추가 요청한다", score: 3 },
      ],
    },
    {
      id: "Q8",
      chapter: "history",
      dimension: "experience",
      type: "single",
      title: "AI를 사용한 뒤 실제 업무 결과물에 반영한 경험은 어느 정도인가요?",
      options: [
        { value: "a", label: "AI를 업무에 사용한 적이 없다", score: 0 },
        { value: "b", label: "답변을 봤지만 실제 결과물에는 쓰지 않았다", score: 1 },
        { value: "c", label: "문장이나 아이디어 일부를 참고했다", score: 2 },
        { value: "d", label: "초안을 받은 뒤 수정해 활용했다", score: 3 },
        { value: "e", label: "업무 과정의 여러 단계에서 활용했다", score: 4 },
      ],
    },
    {
      id: "Q9",
      chapter: "sense",
      dimension: "verification",
      type: "ox",
      title: "AI가 매우 자연스럽고 자신 있게 답했다면 그 내용은 대부분 사실일까요?",
      options: [
        { value: "o", label: "O", score: 0 },
        { value: "x", label: "X", score: 2 },
      ],
      correct: "x",
      explanation:
        "AI는 틀린 내용도 자연스럽게 표현할 수 있어요. 중요한 숫자, 규정, 인명, 일정, 출처는 별도로 확인해야 합니다.",
    },
    {
      id: "Q10",
      chapter: "sense",
      dimension: "security",
      type: "ox",
      title: "공개되지 않은 사내 자료는 이름과 숫자를 조금 바꾸면 어떤 AI에든 입력해도 괜찮을까요?",
      options: [
        { value: "o", label: "O", score: 0 },
        { value: "x", label: "X", score: 2 },
      ],
      correct: "x",
      explanation:
        "일부 내용을 바꿨더라도 문맥으로 정보가 드러날 수 있어요. 회사의 보안 규정과 사용 가능한 AI 도구 범위를 먼저 확인해야 합니다.",
    },
    {
      id: "Q11",
      chapter: "sense",
      dimension: "prompting",
      type: "ox",
      title: "같은 AI라도 질문 방식에 따라 결과가 달라질 수 있을까요?",
      options: [
        { value: "o", label: "O", score: 2 },
        { value: "x", label: "X", score: 0 },
      ],
      correct: "o",
      explanation:
        "목적, 대상, 상황, 조건, 결과물 형식을 구체적으로 알려줄수록 원하는 답을 받을 가능성이 높아집니다.",
    },
    {
      id: "Q12",
      chapter: "sense",
      dimension: "security",
      type: "ox",
      title: "고객의 이름, 전화번호, 상담 내용을 그대로 AI에 입력해 요약을 요청해도 될까요?",
      options: [
        { value: "o", label: "O", score: 0 },
        { value: "x", label: "X", score: 2 },
      ],
      correct: "x",
      explanation:
        "개인정보와 민감정보는 임의로 외부 AI 서비스에 입력하면 안 됩니다. 회사가 승인한 도구와 비식별 처리 기준을 따라야 해요.",
    },
    {
      id: "Q13",
      chapter: "prompt",
      dimension: "prompting",
      type: "single",
      title: "다음 중 가장 좋은 회의 안내 메시지 요청은 무엇일까요?",
      scenario: "다음 주 팀 회의 안내 메시지를 작성해야 한다.",
      options: [
        { value: "a", label: "회의 메시지 써줘.", score: 0 },
        { value: "b", label: "다음 주 팀 회의 안내 메시지를 친절하게 써줘.", score: 1 },
        {
          value: "c",
          label:
            "팀원들에게 보낼 회의 안내 메시지를 작성해줘. 회의는 8월 5일 오후 2시, 4층 회의실에서 진행하고, 안건은 하반기 업무계획이야. 친근하지만 업무적인 톤으로 300자 이내로 작성해줘.",
          score: 3,
        },
        { value: "d", label: "회의 안내 메시지를 길고 자세하게 작성해줘.", score: 0 },
      ],
      correct: "c",
      explanation:
        "좋은 요청에는 대상, 일정, 장소, 목적, 문체, 분량처럼 결과를 결정하는 정보가 포함됩니다.",
    },
    {
      id: "Q14",
      chapter: "prompt",
      dimension: "prompting",
      type: "single",
      title: "엉켜 있는 회의 메모를 정리하려고 합니다. 가장 효과적인 요청은?",
      options: [
        { value: "a", label: "이거 요약해줘.", score: 0 },
        { value: "b", label: "아래 메모를 회의록으로 정리해줘.", score: 1 },
        {
          value: "c",
          label:
            "아래 회의 메모를 주요 논의사항, 결정사항, 담당자, 기한, 추가 확인사항으로 나누어 정리해줘. 불분명한 부분은 임의로 채우지 말고 ‘확인 필요’라고 표시해줘.",
          score: 3,
        },
        { value: "d", label: "아래 내용을 예쁘게 정리해줘.", score: 0 },
      ],
      correct: "c",
      explanation:
        "결과물 항목과 AI가 추측하면 안 되는 기준까지 알려주면 실무에서 바로 쓰기 쉬운 결과를 받을 수 있습니다.",
    },
    {
      id: "Q15",
      chapter: "prompt",
      dimension: "prompting",
      type: "multi",
      scoring: "coreCount",
      maxSelections: 4,
      title: "‘신입사원 교육 아이디어를 추천해줘’를 업그레이드해주세요.",
      helper: "추가하면 좋을 정보 카드를 최대 4개 골라주세요.",
      options: [
        { value: "audience", label: "교육 대상자의 특성", core: true },
        { value: "purpose", label: "교육 목적", core: true },
        { value: "duration", label: "교육 시간", core: true },
        { value: "format", label: "원하는 결과 형식", core: true },
        { value: "weather", label: "오늘의 날씨" },
        { value: "color", label: "내가 좋아하는 색" },
        { value: "floor", label: "회사 건물 층수" },
        { value: "lunch", label: "점심 메뉴" },
      ],
    },
    {
      id: "Q16",
      chapter: "prompt",
      dimension: "prompting",
      type: "single",
      title: "팀장에게 보고할 자료를 요청할 때 가장 실용적인 결과 형식은?",
      options: [
        { value: "a", label: "알아서 보기 좋게 작성해줘", score: 0 },
        { value: "b", label: "자세하게 설명해줘", score: 0 },
        { value: "c", label: "핵심 요약 3줄과 실행 과제 표로 작성해줘", score: 2 },
        { value: "d", label: "최대한 전문적으로 작성해줘", score: 1 },
      ],
      correct: "c",
      explanation:
        "결과 형식을 미리 지정하면 AI 답변을 다시 정리하는 시간을 줄일 수 있습니다.",
    },
    {
      id: "Q17",
      chapter: "prompt",
      dimension: "prompting",
      type: "single",
      title: "AI가 작성한 문장이 너무 딱딱합니다. 다음 행동으로 가장 좋은 것은?",
      options: [
        { value: "a", label: "처음부터 새 대화를 시작한다", score: 1 },
        { value: "b", label: "AI 결과를 포기하고 직접 작성한다", score: 0 },
        { value: "c", label: "대상과 원하는 말투를 설명해 다시 요청한다", score: 3 },
        { value: "d", label: "같은 요청을 그대로 한 번 더 입력한다", score: 0 },
      ],
      correct: "c",
      explanation:
        "첫 답변이 마음에 들지 않아도 수정 방향을 구체적으로 알려주면 결과를 개선할 수 있어요.",
    },
    {
      id: "Q18",
      chapter: "review",
      dimension: "verification",
      type: "single",
      title: "AI가 보고서에 아래 문장을 작성했습니다. 가장 먼저 해야 할 일은?",
      scenario: "“국내 직장인의 92%가 생성형 AI를 매일 업무에 활용하고 있습니다.”",
      options: [
        { value: "a", label: "문장을 더 전문적으로 수정한다", score: 0 },
        { value: "b", label: "숫자의 출처와 조사 기준을 확인한다", score: 3 },
        { value: "c", label: "보고서 디자인을 정리한다", score: 0 },
        { value: "d", label: "수치가 높으므로 강조 표시한다", score: 0 },
      ],
      correct: "b",
      explanation:
        "구체적인 수치가 등장하면 출처, 조사 시점, 조사 대상, 표본을 함께 확인해야 합니다.",
    },
    {
      id: "Q19",
      chapter: "review",
      dimension: "verification",
      type: "single",
      title: "AI가 계산한 예산 합계가 맞는지 확인하려고 합니다. 가장 적절한 행동은?",
      options: [
        { value: "a", label: "AI가 계산했으므로 그대로 사용한다", score: 0 },
        { value: "b", label: "다른 말투로 같은 계산을 다시 요청한다", score: 1 },
        { value: "c", label: "원본 숫자와 계산식을 직접 대조한다", score: 3 },
        { value: "d", label: "숫자가 자연스러워 보이면 사용한다", score: 0 },
      ],
      correct: "c",
      explanation:
        "계산 결과는 원본 데이터, 단위, 수식, 누락값을 직접 확인하는 것이 안전합니다.",
    },
    {
      id: "Q20",
      chapter: "review",
      dimension: "security",
      type: "single",
      title: "다음 중 AI에 입력하기 가장 부적절한 정보는 무엇일까요?",
      options: [
        { value: "a", label: "이미 공개된 회사 홈페이지 문구", score: 0 },
        { value: "b", label: "공개된 보도자료", score: 0 },
        { value: "c", label: "이름과 연락처가 포함된 고객 불만 내용", score: 3 },
        { value: "d", label: "일반적인 회의 진행 방법", score: 0 },
      ],
      correct: "c",
      explanation:
        "개인을 식별할 수 있는 정보와 상담 내용은 민감하게 다뤄야 합니다.",
    },
    {
      id: "Q21",
      chapter: "review",
      dimension: "security",
      type: "single",
      title: "사내 프로젝트 계획을 AI로 정리하고 싶습니다. 가장 적절한 방법은?",
      options: [
        { value: "a", label: "프로젝트명, 예산, 고객사명을 모두 입력한다", score: 0 },
        { value: "b", label: "개인 계정으로 접속해 전체 자료를 첨부한다", score: 0 },
        {
          value: "c",
          label: "회사가 승인한 도구와 기준을 확인한 뒤 필요한 정보만 비식별화해 사용한다",
          score: 3,
        },
        { value: "d", label: "프로젝트명을 이니셜로 바꾸고 전체 자료를 입력한다", score: 1 },
      ],
      correct: "c",
      explanation:
        "단순히 이름을 바꾸는 것만으로는 부족할 수 있어요. 승인된 도구, 이용 목적, 입력 가능 범위를 먼저 확인해야 합니다.",
    },
    {
      id: "Q22",
      chapter: "review",
      dimension: "verification",
      type: "single",
      title: "AI 결과물이 자연스럽고 완성도도 높아 보입니다. 최종 제출 전 가장 좋은 행동은?",
      options: [
        { value: "a", label: "바로 제출한다", score: 0 },
        { value: "b", label: "맞춤법만 확인한다", score: 1 },
        { value: "c", label: "사실, 숫자, 누락, 문맥, 사내 기준을 확인하고 수정한다", score: 3 },
        { value: "d", label: "AI에게 완벽한지 다시 물어본다", score: 1 },
      ],
      correct: "c",
      explanation:
        "AI는 초안 작성자나 보조자 역할을 할 수 있지만 최종 판단과 책임은 사용자에게 있습니다.",
    },
    {
      id: "Q23",
      chapter: "rescue",
      type: "multi",
      tag: "learningNeeds",
      maxSelections: 3,
      title: "AI가 대신 도와줬으면 하는 업무를 최대 3개 골라주세요.",
      options: [
        { value: "message", label: "이메일·메신저 초안" },
        { value: "report", label: "보고서·기획서 초안" },
        { value: "summary", label: "긴 문서 요약" },
        { value: "meeting", label: "회의록 정리" },
        { value: "research", label: "자료 조사" },
        { value: "ideas", label: "아이디어 도출" },
        { value: "presentation", label: "발표자료 구성" },
        { value: "data", label: "엑셀·데이터 처리" },
        { value: "support", label: "반복 문의 답변" },
        { value: "planning", label: "일정·할 일 정리" },
        { value: "translation", label: "문장 교정·번역" },
        { value: "automation", label: "반복 업무 자동화" },
        { value: "unknown", label: "아직 잘 모르겠다", exclusive: true },
      ],
    },
    {
      id: "Q24",
      chapter: "rescue",
      type: "single",
      tag: "learningGoal",
      title: "교육이 끝난 후 가장 달라졌으면 하는 모습은?",
      options: [
        { value: "start", label: "AI에게 무엇을 물어봐야 할지 알고 싶다" },
        { value: "writing", label: "문서 작성 시간을 줄이고 싶다" },
        { value: "quality", label: "보고서나 기획서의 완성도를 높이고 싶다" },
        { value: "research", label: "자료 조사 시간을 줄이고 싶다" },
        { value: "automation", label: "반복 업무를 줄이고 싶다" },
        { value: "verification", label: "AI 답변이 맞는지 판단하고 싶다" },
        { value: "personal", label: "나에게 맞는 AI 활용법을 찾고 싶다" },
        { value: "sharing", label: "동료에게 AI 사용법을 알려줄 수 있고 싶다" },
      ],
    },
    {
      id: "Q25",
      chapter: "rescue",
      type: "single",
      tag: "learningStyle",
      title: "가장 재미있게 참여할 수 있을 것 같은 교육 방식은?",
      options: [
        { value: "follow", label: "설명을 듣고 바로 따라 해보기" },
        { value: "case", label: "실제 업무 사례를 함께 해결하기" },
        { value: "game", label: "팀별 미션과 게임" },
        { value: "personal", label: "개인 업무를 가져와 직접 개선하기" },
        { value: "template", label: "좋은 프롬프트 예시를 받아 연습하기" },
        { value: "demo", label: "자유롭게 질문하고 시연 보기" },
      ],
    },
  ];

  const dimensions = {
    awareness: { label: "AI 친밀도", max: 9, icon: "✨" },
    experience: { label: "활용 경험", max: 16, icon: "🧰" },
    prompting: { label: "질문 설계력", max: 16, icon: "✍️" },
    verification: { label: "결과 검증력", max: 11, icon: "🔎" },
    security: { label: "보안 감수성", max: 10, icon: "🔐" },
  };

  const resultTypes = {
    ai_warmup: {
      name: "AI 워밍업러",
      icon: "🌱",
      color: "#a999ff",
      image: "./assets/results/ai-warmup.png",
      video: "./assets/results/ai-warmup.mp4",
      tagline: "AI와 아직 조금 어색하지만, 이제 막 친해질 준비를 시작한 타입이에요.",
      strength:
        "기존 업무 방식과 기준을 잘 알고 있어요. 단계별로 익히면 안정적으로 성장할 가능성이 높습니다.",
      growth:
        "완벽한 질문을 만들려고 하기보다 작은 업무 한 가지부터 가볍게 맡겨보세요.",
      missions: [
        "장문의 메시지를 3줄로 요약해보기",
        "이메일 제목 5개 추천받기",
        "작성한 문장을 더 자연스럽게 다듬기",
      ],
      cardLine: "오늘은 인사만 나눴지만, 곧 제법 친한 업무 메이트가 될 예정",
    },
    curious_explorer: {
      name: "AI 호기심 탐험가",
      icon: "🧭",
      color: "#709fe7",
      image: "./assets/results/curious-explorer.png",
      video: "./assets/results/curious-explorer.mp4",
      tagline: "관심과 아이디어는 충분하지만, 아직 본격적으로 활용할 기회를 찾는 중이에요.",
      strength:
        "새로운 방식에 열려 있고 교육 참여 동기가 높아요. 구체적인 사례를 만나면 빠르게 시도할 수 있습니다.",
      growth:
        "AI에 대해 더 알아보기보다 오늘 해야 할 일 하나에 직접 적용해보는 것이 중요해요.",
      missions: [
        "내일 할 일의 우선순위를 정리해보기",
        "회의 안건 초안을 만들어보기",
        "보고서 목차를 3가지 버전으로 받아보기",
      ],
      cardLine: "저장해둔 활용법은 많고, 이제 실행 버튼만 누르면 되는 타입",
    },
    prompt_designer: {
      name: "AI 질문 디자이너",
      icon: "✍️",
      color: "#78cfb3",
      image: "./assets/results/prompt-designer.png",
      video: "./assets/results/prompt-designer.mp4",
      tagline: "AI가 알아듣기 쉽게 상황과 조건을 정리하는 감각이 좋은 타입이에요.",
      strength:
        "대상, 목적, 조건과 결과 형식을 구조화하는 능력이 좋아요. AI와의 반복 대화도 능숙합니다.",
      growth:
        "질문을 잘하는 것에 더해 답변의 근거와 정확성까지 확인하면 활용 수준이 크게 높아져요.",
      missions: [
        "같은 내용을 세 가지 톤으로 바꿔보기",
        "초안을 표와 요약문으로 재구성하기",
        "AI 답변에 반론과 누락 사항을 요청하기",
      ],
      cardLine: "AI에게 일을 잘 맡기는 것도 능력이라는 사실을 이미 아는 타입",
    },
    quality_editor: {
      name: "AI 품질 편집자",
      icon: "🔎",
      color: "#ffb45f",
      image: "./assets/results/quality-editor.png",
      video: "./assets/results/quality-editor.mp4",
      tagline: "AI 결과를 그대로 믿기보다 꼼꼼하게 확인하는 안정형 사용자예요.",
      strength:
        "팩트체크와 위험 요소 발견에 강하고, 사내 기준에 맞는 결과물을 만들려는 감각이 좋아요.",
      growth:
        "검증 습관은 유지하되 초안과 아이디어 단계에서는 조금 더 가볍게 AI를 활용해보세요.",
      missions: [
        "AI 초안에서 확인할 항목을 표시하기",
        "출처가 필요한 문장만 추출하기",
        "AI 답변의 반대 의견을 요청하기",
      ],
      cardLine: "AI가 자신 있게 말해도 한 번 더 확인하는 믿음직한 편집자",
    },
    practical_maker: {
      name: "AI 실무 메이커",
      icon: "🛠️",
      color: "#ff8e7a",
      image: "./assets/results/practical-maker.png",
      video: "./assets/results/practical-maker.mp4",
      tagline: "AI를 실제 업무에 연결해 결과물을 만들어본 경험이 있는 실행형이에요.",
      strength:
        "도구에 대한 심리적 장벽이 낮고, 초안과 아이디어를 실제 결과물로 연결하는 힘이 있어요.",
      growth:
        "빠른 실행에 검증 기준과 나만의 업무 절차를 더하면 더 안정적인 활용자가 될 수 있어요.",
      missions: [
        "업무별 프롬프트 템플릿 만들기",
        "AI 결과물 검수 체크리스트 만들기",
        "반복 업무를 단계별로 나눠 AI 적용하기",
      ],
      cardLine: "일단 써보고 쓸 만한 결과는 바로 업무에 가져오는 실전파",
    },
    workflow_director: {
      name: "AI 워크플로우 디렉터",
      icon: "🎬",
      color: "#e97f93",
      image: "./assets/results/workflow-director.png",
      video: "./assets/results/workflow-director.mp4",
      tagline: "질문, 활용, 검증의 균형이 좋은 AI 협업형 사용자예요.",
      strength:
        "AI를 실제 업무에 연결하면서 요청 조건, 결과 형식, 정확성과 보안을 함께 고려할 수 있어요.",
      growth:
        "개인 활용을 넘어 팀 공통 템플릿이나 업무 표준으로 확장해보세요.",
      missions: [
        "팀 공용 프롬프트 템플릿 제작하기",
        "반복 업무의 AI 활용 프로세스 설계하기",
        "동료 한 명의 업무 개선 사례 만들기",
      ],
      cardLine: "AI에게 일을 맡기고, 결과를 편집하고, 업무 방식까지 바꾸는 디렉터",
    },
  };

  window.APP_DATA = {
    chapters,
    jobTasks,
    questions,
    dimensions,
    resultTypes,
  };
})();
